sudo: false
language: go
go:
- 1.4

install:
- go get -v github.com/spf13/hugo

script:
- hugo -v

branches:
  only:
  - master

deploy:
  provider: s3
  access_key_id: AKIAI3MTTXNCRKL4O3IQ
  secret_access_key:
    secure: F+DstXgQ0EHaVg0NY3WGSg94gvu/85Lvevm+pj3Es3scpSwKz8cB29VtClcJc5f6afyRQZgwnS2w5rV/RtwF9ubXZBL1nF/7w8dohRI7C0ZPCcTKGlRKDR3XwmRObrXeD/PYM6Ijx8J9i+m6lZ1qyhQ4OS9CwdfuDJKDSCJWXC0=
  region: us-east-1
  bucket: edmontongo.org
  skip_cleanup: true
  local-dir: public
  acl: public_read
  on:
    repo: edmontongo/edmontongo.org
    # branch: deploy
